### ISSUE TITLE
Build Compiler.

### ISSUE THREAD

**Issue by Spoiledpay** [karol11/argentum#32]
What are the steps and requirements to be able to carry out a compilation on Windows? Code but not how to create an executable. Only the release is ready.
There is no doc or help to create a build from the source code. Can you help with the procedures to follow so we can do this. It would be a great help. Thanks.

**Comment by karol11** [comment]
Done: [build-argentum-from-sources-on-windows](https://aglang.org/build-argentum-from-sources-on-windows/)
