### ISSUE TITLE
The httpDemo example does not work - it requires a non-existent library uuid.lib

### ISSUE THREAD

**Issue by alex1543** [karol11/argentum#34]
Dear Argentum developer!
Help me to understand.
The httpDemo example does not work - it requires a non-existent library uuid.lib
Where can I download?
```
C:\xampp\htdocs\argentum\bin>run-release.bat httpDemo
C:\xampp\htdocs\argentum\workdir>"C:\xampp\htdocs\argentum\bin\agc" -src "..\src" -start httpDemo -O3 -o "httpDemo.obj"
Done httpDemo.obj
lld-link: error: could not open 'uuid.lib': no such file or directory
```

**Comment by karol11** [comment]
My bad, I'll add in in the next "release", right now you can get it from any Windows Kit (usually located at C:\Program Files (x86)\Windows Kits\10\Lib\10.0.20348.0\um\x64
